name: Deploy Vite App to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the workflow when changes are pushed to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use an Ubuntu environment

    steps:
      # 1. Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Set up Node.js with the specified version
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'  # Set Node.js version to match your local environment (v20.x)

      # 3. Install dependencies using npm
      - name: Install dependencies
        run: npm install

      # 4. Build the Vite project using secrets directly in the build command
      - name: Build Vite project
        run: VITE_REACT_APP_EMAILJS_SERVICE_ID=${{ secrets.VITE_REACT_APP_EMAILJS_SERVICE_ID }} \
             VITE_REACT_APP_EMAILJS_PUBLIC_KEY=${{ secrets.VITE_REACT_APP_EMAILJS_PUBLIC_KEY }} \
             VITE_REACT_APP_EMAILJS_TEMPLATE_ID=${{ secrets.VITE_REACT_APP_EMAILJS_TEMPLATE_ID }} \
             npm run build

      # 5. Deploy to GitHub Pages securely using PAT (Personal Access Token)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: './dist'  # Path to the built files
          github_token: ${{ secrets.GH_IO_PAT }}  # Use your stored PAT for authentication
